version: "3.8"
services:
  mysqldb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'vibe'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'