spring:
  main:
    banner-mode: console
  h2:
    console:
      path: /vibe
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vibe
    username: dev
    password: password
  sql:
    init:
      schema-locations: classpath:db/ddl.sql
      data-locations: classpath:db/dml.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    lt:
      vibenchat:
        demo:
          root: INFO